Repository storybookjs/mdx2-csf, pull requests merged in 2022-11, with the labels that each got.

#23 Prebundle with tsup
  compiler.js
  loader.js
  package.json
  src/index.test.ts
  src/index.ts
  src/mdx2.ts
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: patch

#24 Upgrade example to SB7
  .storybook/main.js
  package.json
  stories/Introduction.stories.mdx
  yarn.lock
Labels: skip-release

#25 Fix canvas mdxSource generation and add tests
  .storybook/main.js
  package.json
  src/index.test.ts
  src/index.ts
  src/sb-mdx-plugin.ts
  stories/Button.stories.mdx
  yarn.lock
Labels: bug, patch

#26 Bump version of loader-utils
  package.json
Labels: enhancement
