Repository storybookjs/mdx2-csf, pull requests merged in 2022-10, with the labels that each got.

#14 Remove uses of `AddContext`
  src/mdx2.test.ts
  src/mdx2.ts
  src/sb-mdx-plugin.ts
Labels: minor

#19 chore: Moved @babel/types to dependencies
  package.json
Labels: bug, patch

#20 Remove JSX from compiler output
  src/mdx2.test.ts
  src/sb-mdx-plugin.ts
Labels: enhancement

#22 Add mdx tag for SB7 support
  src/mdx2.test.ts
  src/sb-mdx-plugin.ts
Labels: enhancement
